micronaut:
  application:
    name: micronautuserService
  server:
    port: ${SERVER_PORT:8080}

datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-db
    username: root
    password: Ajay@123
    schema-generate: CREATE_DROP
    db-type: mysql
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          #auto: update  not to be used in case of flyway
           auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
shedlock:
  defaults:
    lock-at-most-for: 1m
#netty:
  #default:
    #allocator:
     # max-order: 3
